### ISSUE TITLE
Compile error in vulkan-lib.scm 

### ISSUE THREAD

**Issue by nkoguro** [shirok/Gauche-gl#14]
It looks like vulkan-lib.scm can't be compiled in HEAD.
https://gist.github.com/nkoguro/2803db3a836a23a953822c5303e7fb28

I use WSL2 + WSLg and the compile error may be an environment-dependent problem.

**Comment by shirok** [comment]
I found that vulkan header is frequently updated, and even though VK_VERSION is same (1.0.1), headers of different version (VK_HEADER_VERSION) define different symbols.  I need to figure out how to cope with their changes.

**Comment by shirok** [comment]
Last couple of commits should fix it.

**Comment by nkoguro** [comment]
vulkan-lib.scm can be compiled now.
Thanks!
